In [1]:
import numpy as np

In [7]:
x = np.array([1.0, 2.0, 3.0])

In [8]:
print(x)

[1. 2. 3.]


In [9]:
type(x)

numpy.ndarray

In [10]:
y = np.array([4.0, 5.0, 6.0])

In [11]:
x+y

array([5., 7., 9.])

In [12]:
A = np.array([[1,3], [2,4]])

In [13]:
print(A)

[[1 3]
 [2 4]]


In [14]:
print(A[0])

[1 3]


In [15]:
for row in A:
    print(row)

[1 3]
[2 4]
